language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
